repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: nailtrial
  description: Trial of nail for generating functional profiles instead of HMMer hmmsearch.
  author: "@timrozday-mgnify"
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
